---
- name: Run common setup
  hosts: all
  roles: [common]
- name: Deploy Docker
  hosts: docker
  roles: [docker]
- name: Deploy Minecraft
  hosts: microwave
  roles: [minecraft]
- name: Clean up Docker resources
  hosts: docker
  tasks:
    - name: Clean up Docker resources
      community.docker.docker_prune:
        images: true
        containers: true
