services:
  anubis:
    image: 'ghcr.io/letsbuilda/anubis:edge'
    pull_policy: 'always'
    restart: 'always'
    env_file:
      - '/opt/letsbuilda/discord-bots/anubis-env.list'

  alessia:
    image: 'ghcr.io/letsbuilda/alessia:edge'
    pull_policy: 'always'
    restart: 'always'
    env_file:
      - '/opt/letsbuilda/discord-bots/alessia-env.list'

  letsbuilda-discord-bots-postgres:
    image: 'postgres:15.0'
    pull_policy: 'always'
    restart: 'always'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=changemeplz'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5432:5432'
    volumes:
      - '/opt/letsbuilda/discord-bots/pg-data:/var/lib/postgresql/data'
